### ISSUE TITLE
Polymer conflict with Vaadin 14.1.3

### ISSUE THREAD

**Issue by sonnessa** [pleku/wysiwyg-e-java#16]
Dear pekka,
I had a working example of Vaadin app integrating your component.

Switching from Vaadin Flow 14.0 up to 14.1.3 the component caused the following error in the browser:

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
    at eval (webpack-internal:///../node_modules/@polymer/paper-dropdown-menu/node_modules/@polymer/polymer/lib/elements/dom-module.js?babel-target=es6:181:16)

I got the same issue in another project too. The problem seems related to polymer version incompatibility.

Can you help me?

Thanks in advance,
Michele Sonnessa

**Comment by sascha-broich** [comment]
I got this problem too. 
To find the root cause I looked deeper.
And found that the package @polymer/paper-dropdown-menu got updated to 3.1.0 three weeks ago and requires now polymer 3.3.1.
Because wysiwyg-e-fork declares the version to be at least 3.0.1 the result is now the conflict of polymer 3.2.0 from Vaadin and polymer 3.3.1 from the addon.

**Comment by sonnessa** [comment]
Thanks for the suggestion.
I fixed the problem using the fork at https://github.com/zero11it/wysiwyg-e
@polymer/paper-dropdown-menu is imported with patch notation instead of minor version.

**Comment by Nuraddin** [comment]
> Thanks for the suggestion.
> I fixed the problem using the fork at https://github.com/zero11it/wysiwyg-e
> @polymer/paper-dropdown-menu is imported with patch notation instead of minor version.

Give me please example how to use fork in vaadin application. How to point fork url in vaadin?
