### ISSUE TITLE
Exclude vaadin bom from jar file

### ISSUE THREAD

**Issue by xadagaras** [pleku/wysiwyg-e-java#3]
Hi,

I tried to add your addon to my project, but it fails because he tries to resolve the vaadin-bom in version 10.0.0.rc5 which is not in our companies artifactory (and will not land there since the release version is available).

So please remove the bom from the final jar or update to the latest release version.

Normaly this bom should not be part of the final jar file because you could get version conflicts.

**Comment by pleku** [comment]
Hi. I'm not sure it is wise to remove the bom completely, since it is not always possible to use the component with another platform version than what it is built on top of. 

But I believe it is a "feature" of Maven to try to read all the dependencies before trying to resolve them. So thus you could have probably fixed this by using an exclusion.

However, I can refactor the dependencies so that those are scoped accordingly and will not leak into your project.
