### ISSUE TITLE
2.0.0.alpha1 broken due to absolulte paths

### ISSUE THREAD

**Issue by roacer** [pleku/wysiwyg-e-java#8]
Hi,

I added the dependency for 2.0.0.alpha1 to my pom. Now the project won't start anymore:

`java.lang.IllegalArgumentException: 'other' is different type of Path`

this is most likely caused by flow-build-info.json:

`{
  "compatibilityMode": false,
  "productionMode": false,
  "npmFolder": "C:\\Users\\Pekka\\workspaces\\flow\\wysiwyg-e-java",
  "generatedFolder": "C:\\Users\\Pekka\\workspaces\\flow\\wysiwyg-e-java\\target\\frontend",
  "frontendFolder": "C:\\Users\\Pekka\\workspaces\\flow\\wysiwyg-e-java\\frontend"
}`

Why are there absolute paths in there? And where does the file come from? I can't see it in the repository.

BR,

Daniel

**Comment by pleku** [comment]
Hi, thanks for the report, for some reason I've been unwatching the repository so I missed this message, my bad.

This is due to the add-on containing some build files that should not be there. I think it was fixed in some Vaadin 14.0.x maintenance version to not look for those files from the `.jar`, but I will make sure those will not be added when releasing next version of the add-on.
